id: ID8D2952F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:10:29+00:00'
last_modified: '2022-06-07T12:14:28.408188+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6048
  title: ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E3DF:
      image_group_id: I1KG6271
      title: Volume 1 of zhi khro dgongs pa rang grol
      total_pages: 238
      order: 1
      base_file: E3DF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
